- name: app-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Maven-Setup
  ansible.builtin.import_role:
    name: common
    tasks_from: maven-setup



- name: importing data into 
  community.mysql.mysql_db:
    name: all
    login_user: root
    login_password: RoboShop@1
    login_host: mysql.autonagar.in
    state: import
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql 
  - /app/db/master-data.sql

- name: Shipping systemd-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup