- name: creating roboshop user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    system: true
    home: /app

- name: creating a directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: "downloading {{ component }} url"
  ansible.builtin.get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip"
    dest: "/tmp/{{ component }}.zip"

- name: "extracting {{ component }} url"
  ansible.builtin.unarchive:
    src: "/tmp/{{ component }}.zip"
    dest: /app
    remote_src: yes

- name: Installing npm package
  community.general.npm:
    path: /app